### ISSUE TITLE
SvelteKit restart

### ISSUE THREAD

**Issue by karnikaavelumani** [acmcsufoss/form#11]
### Goal

Write this project ([design document](https://docs.google.com/document/d/1niauzhRJvguOHVpLDqfKOLpjfgRg_Ew9sX9QfEsU4bs/edit)) in [SvelteKit](https://kit.svelte.dev/).

### Assignees

- @AlexthePear 
- @k8iekitkat 

### References

1. [WIP Pydantic types](https://github.com/acmcsufoss/form/blob/581e2cea7ed0b0b873c61b05cb5a9c4d9606f99b/form/form.py) - WIP Form represented in Python/Pydantic.
2. [Svelte Basics](https://acmcsuf.com/basics) - An introductory guide blog post to Svelte.
3. [Svelte Tutorial](https://learn.svelte.dev/tutorial/welcome-to-svelte) - Official Svelte tutorial for getting started.

**Comment by EthanThatOneKid** [comment]
Resolved in #12 thanks to @AlexthePear and @k8iekitkat :godmode:
